permalink: /:year:month:day/:title
url: #Your url here
baseurl: /

# variables
name: Daniel G&ouml;ller
description: Data scientist &middot; .NET developer &middot; hobby-linguist
google_verification: null


# File management
include: [".htaccess", ".well-known"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

# Plugins
plugins:
  - jekyll-redirect-from